#' 100 simulated data matrices 
#'
#'  Contains the 100 simulated matrices generated by Congreve & Lamsdell (2016) using a 
#'  heterogeneous Markov-k model, generated from the \link{referenceTree} topology, with 
#'  all branches sharing an equal length.
#'
#' @format A list with 100 entries, each comprising a phyDat object of 55 characters for 22 taxa
#'
#' @references 
#' Congreve, C. R., & Lamsdell, J. C. (2016). \cite{Implied weighting and its utility in 
#'   palaeontological datasets: a study using modelled phylogenetic matrices.} Palaeontology, 
#'   online ahead of print. doi:10.1111/pala.12236
#' 
#' Congreve, C. R., & Lamsdell, J. C. (2016). Data from: Implied weighting and its utility in 
#' palaeontological datasets: a study using modelled phylogenetic matrices. Dryad Digital
#' Repository, \href{http://dx.doi.org/10.5061/dryad.7dq0j}{doi:10.5061/dryad.7dq0j}
#' 
#' @examples 
#'   data('referenceTree')
#'   data('congreveLamsdellMatrices')
#'   ProfileScore(referenceTree, PrepareDataProfile(congreveLamsdellMatrices[[17]]))
#'
#' @source \url{http://datadryad.org/resource/doi:10.5061/dryad.7dq0j}
"congreveLamsdellMatrices"

#' Tree topology for matrix simulation
#'
#' The tree topology used to generate the matrices in \code{\link{congreveLamsdellMatrices}} 
#' Congreve & Lamsdell (2016)
#'
#' @format A single phylogenetic tree saved as an object of class \code{phylo}
#'
#' @references 
#' Congreve, C. R., & Lamsdell, J. C. (2016). \cite{Implied weighting and its utility in 
#'   palaeontological datasets: a study using modelled phylogenetic matrices.} Palaeontology, 
#'   online ahead of print. doi:10.1111/pala.12236
#' 
#' Congreve, C. R., & Lamsdell, J. C. (2016). Data from: Implied weighting and its utility in 
#' palaeontological datasets: a study using modelled phylogenetic matrices. Dryad Digital
#' Repository, \href{http://dx.doi.org/10.5061/dryad.7dq0j}{doi:10.5061/dryad.7dq0j}
#' 
#' @examples 
#'   data(referenceTree)
#'   plot(referenceTree)
#' 
#' @source \url{http://dx.doi.org/10.1111/pala.12236}
"referenceTree"